---
openapi: 3.0.1
info:
  title: This web creates short url. It looks like a clone of bit.ly
  version: ''
  description: 'Create short url, Get original link, Destroy url from database '
paths:
  "/transformers":
    post:
      summary: ''
      tags:
      - Create short link
      parameters: []
      responses:
        '200':
          description: short url created
          content: {}
        '422':
          description: invalid url
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_url:
                  type: string
              required:
              - user_url
  "/{nickname}":
    get:
      summary: ''
      tags:
      - Show link
      parameters:
      - name: nickname
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: get url
          content: {}
        '404':
          description: invalid request
          content: {}
  "/transformers/{nickname}":
    delete:
      summary: ''
      tags:
      - Destroy saved link and short url
      parameters:
      - name: nickname
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: No content
          content: {}
        '404':
          description: not_found
          content: {}
