---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/transformers":
    post:
      summary: 'Creates '
      tags:
      - create nickname
      parameters: []
      responses:
        '200':
          description: transformer created
          content: {}
        '302':
          description: invalid url
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_url:
                  type: string
              required:
              - user_url
  "/{nickname}":
    get:
      summary: 'gets '
      tags:
      - show link
      parameters:
      - name: nickname
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: transformer gets
          content: {}
        '404':
          description: invalid request
          content: {}
  "/transformers/{nickname}":
    delete:
      summary: destroy nickname
      tags:
      - destroy link and nickname
      parameters:
      - name: nickname
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: No content
          content: {}
        '404':
          description: not_found
          content: {}
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
