---
openapi: 3.0.1
info:
  title: This web-app creates short url.
  version: ''
  description: |-
    Description:

              It works similar to bit.ly.
              This app creates short url for long links. You can find it after: 'redirect_url:'
              When it has been created, you can use it in messages where it requires limited numbers of symbols.
              In order to get original link, just paste short url to browser's address bar and press 'Enter'.
              If you do not need this link, you can delete it from database just using nickname.
paths:
  "/transformers":
    post:
      summary: 'Creates '
      tags:
      - Create short url
      parameters: []
      responses:
        '200':
          description: short url created
          content: {}
        '422':
          description: invalid url
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_url:
                  type: string
              required:
              - user_url
  "/transformers/{nickname}":
    delete:
      summary: Destroy saved short link
      tags:
      - destroy link and short url
      parameters:
      - name: nickname
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: No content
          content: {}
        '404':
          description: not_found
          content: {}
